name: Pylint

on: [push]

jobs:
  pylint:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/setup.yml
    steps:
    - name: Install pylint
      run: |
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint ./assdialoguemerger/
