name: Pylint

on: [push]

jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  pylint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - uses: actions/checkout@v3
    - name: Install pylint
      run: |
        pip install pylint
    - name: Run pylint
      run: |
        pylint ./assdialoguemerger/